my_string = input("Для подсчета символов введите текст: ")
entered_text = len(my_string)
print("Количество символов в вашем тексте: ", entered_text)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string[0])
print(my_string[-1])